name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 라이브러리 설치
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: EXE 빌드
      run: |
        pyinstaller --onefile --windowed main.py

    - name: 결과 업로드
      uses: actions/upload-artifact@v4
      with:
        name: hwpx-merge-exe
        path: dist/main.exe
